# Generated by Django 2.0 on 2017-12-29 20:15

from django.db import migrations


def create_products(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')

    Product(sku='P1C1',name='Product 1', description='Product 1', buyPrice=100 , sellPrice=100,unit='kilogram', quantity=100).save()
    Product(sku='P2C2',name='Product 2', description='Product 2', buyPrice=100 , sellPrice=100,unit='kilogram', quantity=200).save()
    Product(sku='P3C1',name='Product 3', description='Product 3', buyPrice=100 , sellPrice=100,unit='kilogram', quantity=300).save()
    Product(sku='P4C3',name='Product 4', description='Product 4', buyPrice=100 , sellPrice=100,unit='kilogram', quantity=400).save()
    Product(sku='P5C1',name='Product 5', description='Product 5', buyPrice=100 , sellPrice=100,unit='kilogram', quantity=100).save()
    Product(sku='P6C2',name='Product 6', description='Product 6', buyPrice=100 , sellPrice=100,unit='kilogram', quantity=200).save()
    Product(sku='P7C1',name='Product 7', description='Product 7', buyPrice=100 , sellPrice=100,unit='kilogram', quantity=300).save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_products),
    ]
